name: Test
on:
  push:
    branches:
    - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install newman
        run: npm install -g newman
      - name: Install newman HTML reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir testResults
      - name: Run POSTMAN collection
        if: always()
        run: newman run petstore_collection.json -r cli,htmlextra --reporter-htmlextra-export ./testResults/htmlreport.html
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: ./testResults
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: testResults
          target-folder: docs